Master
openconnectivityfoundation/core pull request #101
Opened 2017-10-31 14:39 UTC by mjkoster

Added  the file oic.wk.col.atomic.raml

2017-11-07 02:56 UTC, rabardini commented on oic.wk.col.atomic.raml
> +      If a client attempts to access an item in an Atomic Measurement individually,
Remove descriptive text that is a duplicate of the Core spec.  Also do not put any "normative" text in comments.

2017-11-07 02:57 UTC, rabardini commented on oic.wk.col.atomic.raml
> +  - diag-payload: !include schemas/oic.diag-payload-schema.json
Remove oic.diag-payload-schema.json

2017-11-07 03:04 UTC, rabardini commented on oic.wk.col.atomic.raml
> +  post:
Remove "post" from RAML file as UPDATE is prohibited.

2017-11-07 03:06 UTC, rabardini commented on oic.wk.col.atomic.raml
> +          description: "All targets returned OK status (HTTP 200 or CoAP 2.05 Content)"
Reword description and do not put quotes in the description text.

2017-11-07 03:34 UTC, rabardini commented on oic.wk.col.atomic.raml
> +                        "datetime": "2007-04-05T14:30+09:00"
datetime -> observedtime

2017-11-07 03:35 UTC, rabardini commented on oic.wk.col.atomic.raml
> +        500:
Remove the 500 response block.

2017-11-07 03:36 UTC, rabardini commented on oic.wk.col.atomic.raml
> +    displayName: Batch Representation
should be linked list representation not bath representation

2018-01-14 23:48 UTC, mjkoster commented
Removed all of the normative and quasi-normative text as per the above comment

2018-03-27 17:40 UTC, mkettrick commented on oic.wk.atomicmeasurement.raml
> +      thus ensuring that all of the items are accessed "atomically" in the batch.
Actually, you can find the Properties of the AM Resource itself using baseline or ll, so this needs to be reworded slightly to state the it's talking about the Properties of the linked Resources.

2018-03-27 17:40 UTC, mkettrick commented on oic.wk.atomicmeasurement.raml
> +                        "observedtime": "2007-04-05T14:30+09:00"
Did the Property Name of the timestamp Resource change to something else other than "observedtime"?  I can't remember but I recall talking about it when reviewing the HC data models.

2018-03-27 17:40 UTC, mkettrick commented on oic.wk.atomicmeasurement.raml
> +      for each interface which is supported by the collection.
"by the collection" should be change to "by the Atomic Measurement"

2018-03-27 17:40 UTC, mkettrick commented on oic.wk.atomicmeasurement.raml
> +                "links": [
Should we add "rts-m" here as well?

2018-03-27 17:40 UTC, mkettrick commented on oic.wk.atomicmeasurement.raml
> +                "rt": ["oic.wk.col.atomic"],
This is the wrong "rt" value, right?  I think it was changed to oic.wk.atomicmeasurement.

2018-03-27 17:40 UTC, mkettrick commented on oic.wk.atomicmeasurement.raml
> +                    "rt":   ["oic.r.time.observed"],
I can't find a schema for this but I did find one for oic.r.time.stamp.  Did that new schema replace this one?

2018-03-27 17:40 UTC, mkettrick commented on oic.wk.atomicmeasurement.raml
> +                        "observedtime": "2007-04-05T14:30+09:00"
If this is in fact oic.r.time.stamp, then the Property name is now called "timestamp".

2018-04-11 08:53 UTC, jacekhryszkiewicz requested changes
Missing comma in line 77

2018-06-12 14:52 UTC, merged